[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
ctrlc = "3.4.5"
libc = "0.2.168"
rand = "0.8.5"
rustix = { version = "0.38.42", features = ["mm", "shm"] }
shared = { path = "../shared" }
