[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
ctrlc = "3.4.5"
rustix = { version = "0.38.42", features = ["shm"] }
shared = { path = "../shared" }

[lints.clippy]
large-stack-frames = "deny"
